# Install teleport on Ubuntu

- name: Download Teleport's PGP public key
  get_url:
    url: https://deb.releases.teleport.dev/teleport-pubkey.asc
    dest: /usr/share/keyrings/teleport-archive-keyring.asc

- name: Add the Teleport APT repository
  #command: echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://deb.releases.teleport.dev/ stable main" > /etc/apt/sources.list.d/teleport.list
  apt_repository: 
    repo: deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://deb.releases.teleport.dev/ stable main
    state: present 
    filename: /etc/apt/sources.list.d/teleport.list

- name: Update apt-get repo and cache
  apt:
    update_cache: yes 
    force_apt_get: yes 

- name: Install teleport package
  apt: 
    name: teleport
    state: present

- name: Add config teleport
  template:
    src: teleport.yaml.j2
    dest: /etc/teleport.yaml

#- name: Enable server teleport start on boot
#  systemd:
#    name: teleport
#    enabled: yes
#    masked: no

- name: Copy file systemd teleport.service
  copy: 
    src: "teleport.service"
    dest: /lib/systemd/system/teleport.service

- name: Reload daemon systemd
  systemd:
    daemon_reload: yes

- name: Restart service Teleport
  service:
    name: teleport
    state: restarted

- name: Copy roles template to server
  copy:
    src: "{{ item }}"
    dest: /tmp/
  with_items: 
    - admin_role.yaml
    - user_role.yaml

- name: Create roles teleport
  shell: |
    /usr/local/bin/tctl create -f /tmp/admin_role.yaml
    /usr/local/bin/tctl create -f /tmp/user_role.yaml

